name: Deploy Backend

on:
  push:
    branches:
      - main   # change if using another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/Food-price-Cambodia-dashboard

            echo "Pull latest code"
            git pull origin main

            echo "Install dependencies"
            npm install

            echo "Build project"
            npm run build

            npm install -g pm2

            echo "Restart PM2"
            pm2 restart myapp || pm2 start npm --name myapp -- start

            echo "Save PM2"
            pm2 save
